---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sprayproxy-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/redhat-appstudio/sprayproxy:{{revision}}"
    - name: infra-deployment-update-script
      value: |
        sed -i -E 's/[0-9a-f]{40}/{{ revision }}/g' components/sprayproxy/staging/kustomization.yaml
  pipelineRef:
    params:
      - name: bundle
        value: >-
          quay.io/redhat-appstudio-tekton-catalog/pipeline-core-services-docker-build:latest
      - name: name
        value: docker-build
      - name: kind
        value: Pipeline
    resolver: bundles
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
